In [20]:
import numpy as np
from scipy import linalg

In [21]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[0.5],[1.0]])

In [22]:
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
mat2

array([[0.5],
       [1. ]])

In [24]:
2 * mat1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
mat1 + mat2

array([[1.5, 2.5, 3.5],
       [5. , 6. , 7. ]])

In [26]:
mat3 = np.array([[3,2,1],[6,5,4]])

In [27]:
mat3

array([[3, 2, 1],
       [6, 5, 4]])

In [28]:
mat1 + mat3

array([[ 4,  4,  4],
       [10, 10, 10]])

In [29]:
mat4 = mat1 * mat1

In [30]:
mat4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
mat5 = mat1.dot(mat1)

ValueError: ignored

In [ ]:
mat5 = mat1.dot(mat1.T)

In [32]:
mat5

array([[14, 32],
       [32, 77]])

In [33]:
mat1.T.dot(mat1)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [34]:
mat3 = linalg.inv(mat1)

ValueError: ignored

In [35]:
mat3 = linalg.inv(mat5)

In [36]:
mat3

array([[ 1.42592593, -0.59259259],
       [-0.59259259,  0.25925926]])

In [37]:
mat5

array([[14, 32],
       [32, 77]])