# Boston housing price regression dataset
Dataset taken from the StatLib library which is maintained at Carnegie Mellon University.

Samples contain 13 attributes of houses at different locations around the Boston suburbs in the late 1970s. Targets are the median values of the houses at a location (in k$).

Firstly, let's select TensorFlow version 2.x in colab

In [1]:
%tensorflow_version 2.x
import tensorflow
tensorflow.__version__

'2.4.1'

In [2]:
# Initialize the random number generator
import random
random.seed(0)

# Ignore the warnings
import warnings
warnings.filterwarnings("ignore")

### Import dataset
- This dataset can be imported
- High level API Keras has some datasets available
- You can look at all the datasets available here https://keras.io/datasets/


In [3]:
from tensorflow.keras.datasets import boston_housing

# boston_housing.load_data() function returns 2 tuples, one for train data and 
# other for test data. We will take only train data here.
(features, actual_prices), _ = boston_housing.load_data(test_split=0)

57344/57026 [==============================] - 0s 0us/step


### Getting details of dataset
- We will see how many rows are there in the data
- We will check how many features are there

In [6]:
print('Number of examples: ', features.shape[0])
print('Number of features for each example: ', features.shape[1])
print('Shape of actual prices data: ', actual_prices.shape)

Number of examples:  506
Number of features for each example:  13
Shape of actual prices data:  (506,)


In [8]:
features

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [1.83377e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.89610e+02, 1.92000e+00],
       [3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [2.92400e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.40160e+02, 9.81000e+00]])

Let's see some values of features and labels from the dataset

In [9]:
features[:5]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00],
       [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
        6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
        2.02000e+01, 3.96900e+02, 8.01000e+00],
       [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
        6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.91430e+02, 1.46500e+01]])

In [10]:
actual_prices[:5]

array([15.2, 42.3, 50. , 21.1, 17.7])

### Build the model
- The Sequential model is a linear stack of layers.
- The model needs to know what input shape it should expect. For this reason, the first layer in a Sequential model (and only the first, because following layers can do automatic shape inference) needs to receive information about its input shape.
- You can also simply add layers via the .add() method

In [11]:
# Initialize Sequential model
model = tensorflow.keras.models.Sequential()

# Normalize input data
model.add(tensorflow.keras.layers.BatchNormalization(input_shape=(13,)))

# Add final Dense layer for prediction - Tensorflow.keras declares weights and bias automatically
model.add(tensorflow.keras.layers.Dense(1))

### Compile the model
- Here we configure the model for training
- We will specify an optimizer and a loss function

In [12]:
# Compile the model - add mean squared error as loss and stochastic gradient descent as optimizer
model.compile(optimizer='sgd', loss='mse')

### Fit the model
- .fit() trains the model for a fixed number of epochs (iterations on a dataset)
- An epoch is an iteration over the entire x and y data provided

In [13]:
model.fit(features, actual_prices, epochs=100, validation_split=0.35)

Epoch 1/100
11/11 [==============================] - 3s 16ms/step - loss: 397.6988 - val_loss: 438.7096
Epoch 2/100
11/11 [==============================] - 0s 5ms/step - loss: 75.8277 - val_loss: 142.1755
Epoch 3/100
11/11 [==============================] - 0s 5ms/step - loss: 73.0797 - val_loss: 93.3884
Epoch 4/100
11/11 [==============================] - 0s 4ms/step - loss: 36.5286 - val_loss: 114.0717
Epoch 5/100
11/11 [==============================] - 0s 5ms/step - loss: 37.4442 - val_loss: 260.4912
Epoch 6/100
11/11 [==============================] - 0s 4ms/step - loss: 36.6500 - val_loss: 54.4583
Epoch 7/100
11/11 [==============================] - 0s 5ms/step - loss: 31.9884 - val_loss: 30.2246
Epoch 8/100
11/11 [==============================] - 0s 4ms/step - loss: 35.4847 - val_loss: 28.7063
Epoch 9/100
11/11 [==============================] - 0s 4ms/step - loss: 34.9403 - val_loss: 26.8549
Epoch 10/100
11/11 [==============================] - 0s 5ms/step - loss: 30.0484 - v

In [14]:
import numpy as np
test_x = np.reshape([1.2, 0, 8.14e+00, 0.0e+00, 5.3e-01, 6.14e+00, 9.170e+01, 3.97e+00, 4, 3.07e+02, 2.10e+01, 3.96e+02, 1.872e+01],(-1, 13))

test_y = model.predict(test_x)

print(test_y)

[[14.878177]]
